spring:
  application:
    name: pubsub-example
    description: Message Brooker using pubsub
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  beaninfo:
    ignore: true
server:
  address: 0.0.0.0
  port: 8080
  error:
    whitelabel:
      enabled: false
gcp:
  pubsub:
    topics:
      exampleTopic: business-example
    subscriptions:
      exampleSubscription: business-example-sub
---
spring:
  profiles:
    active: local

  cloud:
    gcp:
      project-id: pubsub-example-368303
    pubsub:
      enabled: true
